-- ============================================================
-- Seed: PhytotherapyPlant
-- 55 plantas medicinais utilizadas em homeopatia e fitoterapia
-- Fontes: RENISUS/MS, Farmacopeia Brasileira, ANVISA,
--         Farmacopeia Homeopatica Brasileira
-- ============================================================

INSERT INTO "PhytotherapyPlant" ("name", "scientificName", "commonNames", "indications", "contraindications", "preparation", "dosage", "interactions", "notes") VALUES

-- 1. Alcachofra
('Alcachofra',
 'Cynara scolymus L.',
 'Alcachofra, Alcachofra-hortense, Cardo-de-comer',
 'Dispepsia funcional, flatulencia, auxiliar no tratamento de dislipidemia leve a moderada, hepatoprotetor, colagogo e colerético.',
 'Contraindicada em gestantes (efeito emenagogo), lactantes, menores de 12 anos, hipersensibilidade a Asteraceae, obstrucao dos ductos biliares. Nao usar com anticoagulantes.',
 'Infusao: 10 g de folhas secas em 1 litro de agua fervente, abafar por 10 min. Tomar 1 xicara apos as refeicoes principais. Extrato seco padronizado em capsulas.',
 'Extrato seco: 24 a 48 mg de derivados de acido cafeoilquinico por dia. Comprimidos: 2 comprimidos, 3 a 4 vezes ao dia.',
 'Pode potencializar efeito de diureticos. Cautela com anti-hipertensivos e cardiotonicos.',
 'RENISUS/RENAME. Fitoterapico disponivel no SUS. Remedio homeopatico relacionado: Cynara scolymus.'),

-- 2. Espinheira-Santa
('Espinheira-Santa',
 'Maytenus ilicifolia Mart. ex Reissek',
 'Espinheira-santa, Cancerosa, Cangorosa, Maiteno',
 'Dispepsia, gastrite cronica, coadjuvante no tratamento de ulcera gastrica e duodenal. Acao antiulcera, anti-inflamatoria e antioxidante.',
 'Contraindicada na gravidez (pode provocar contracoes uterinas), lactacao (pode diminuir secrecao de leite) e menores de 12 anos. Hipersensibilidade a Celastraceae. Evitar com anabolizantes, antiarritmicos, antifungicos e imunossupressores.',
 'Infusao: 1 a 2 colheres de sopa de folhas secas em 200 mL de agua fervente, abafar por 10 min. Extrato fluido ou capsulas.',
 'Capsulas: 380 mg, 3 vezes ao dia antes das refeicoes. Extrato fluido: 15 a 20 gotas em 200 mL de agua, 3 vezes ao dia apos refeicoes.',
 'Evitar associacao com bebidas alcoolicas. Pode causar boca seca e nauseas em doses elevadas.',
 'RENISUS/RENAME. Fitoterapico disponivel no SUS. Remedio homeopatico relacionado: Maytenus ilicifolia.'),

-- 3. Guaco
('Guaco',
 'Mikania glomerata Spreng.',
 'Guaco, Guaco-cheiroso, Guaco-trepador, Erva-de-serpente',
 'Expectorante e broncodilatador. Auxilia no tratamento de tosses persistentes, bronquite, asma, gripe e rouquidao.',
 'Contraindicado em gestantes, lactantes, criancas menores de 2 anos, hepatopatias cronicas e hipertensos graves. Evitar uso prolongado por mais de 30 dias.',
 'Xarope padronizado (principal forma no SUS). Infusao: 3 g de folhas secas em 150 mL de agua fervente, abafar por 10 min.',
 'Xarope: adultos 10 mL, 3 vezes ao dia. Criancas maiores de 5 anos: metade da dose. Criancas de 2 a 5 anos: 1/3 da dose. Dose diaria de cumarina: 0,5 a 5 mg.',
 'Potencializa efeito de anticoagulantes (presenca de cumarinas). Altas doses podem causar vomitos e diarreias. Uso cronico pode aumentar tempo de protrombina.',
 'RENISUS/RENAME. Fitoterapico disponivel no SUS. Remedio homeopatico relacionado: Mikania glomerata.'),

-- 4. Camomila
('Camomila',
 'Matricaria chamomilla L.',
 'Camomila, Camomila-alema, Macela, Marcela-galega',
 'Ansiolitico e sedativo leve, anti-inflamatorio, antiespasmocido, digestivo. Util em colicas infantis, ansiedade e disturbios do sono.',
 'Contraindicada em hipersensibilidade a Asteraceae. Nao usar em gestantes, lactantes e criancas menores de 6 meses (via oral) ou menores de 12 anos (uso externo).',
 'Infusao: 6 a 9 g de capitulos florais secos em 150 mL de agua fervente, abafar por 10 min. Uso externo: compressas com infusao concentrada.',
 'Cha: 1 a 2 xicaras ao dia. Tintura: 30 a 40 gotas, 3 vezes ao dia diluidas em agua.',
 'Pode causar nauseas, insonia, excitacao nervosa, dermatite de contato e dispneia em individuos sensiveis.',
 'RENISUS. Remedio homeopatico relacionado: Chamomilla (Chamomilla vulgaris).'),

-- 5. Maracuja
('Maracuja',
 'Passiflora incarnata L.',
 'Maracuja, Flor-da-paixao, Passiflora',
 'Ansiolitico natural, sedativo leve, antiespasmocido. Auxilia no alivio de sintomas da ansiedade e insonia.',
 'Pode provocar sonolencia (prejudica direcao e operacao de maquinas). Nao usar com anticoagulantes, barbituricos e inibidores da MAO. Evitar em gestantes.',
 'Infusao: 1 a 2 g de partes aereas secas em 150 mL de agua fervente, abafar por 10 min. Extrato seco padronizado em comprimidos ou solucao oral.',
 'Extrato seco: conforme padronizacao do fabricante. Cha: 1 a 2 xicaras ao dia, preferencialmente a noite.',
 'Potencializa efeito de depressores do SNC (barbituricos, benzodiazepinicos, anti-histaminicos).',
 'RENISUS/RENAME. Fitoterapico disponivel no SUS. Remedio homeopatico relacionado: Passiflora incarnata.'),

-- 6. Curcuma
('Curcuma',
 'Curcuma longa L.',
 'Curcuma, Acafrao-da-terra, Acafrao, Gengibre-amarelo, Turmenique',
 'Anti-inflamatorio (artrite reumatoide, osteoartrite, reumatismo). Antioxidante, auxiliar na reducao de colesterol LDL e protecao hepatica.',
 'Contraindicada em ulceras gastricas, litiase biliar. Nao usar com anticoagulantes (risco de hemorragias) e anti-inflamatorios. Cautela com imunossupressores.',
 'Po do rizoma seco em capsulas ou adicionado a alimentos. Extrato seco padronizado em curcuminoides.',
 'Extrato seco padronizado (95% curcuminoides): 300 a 600 mg, 3 vezes ao dia, com alimentos. Po do rizoma: 1 a 3 g ao dia.',
 'Interacoes com anticoagulantes (varfarina), anti-inflamatorios, imunossupressores, irinotecano e cotrimoxazol.',
 'RENISUS. Remedio homeopatico relacionado: Curcuma longa.'),

-- 7. Gengibre
('Gengibre',
 'Zingiber officinale Roscoe',
 'Gengibre, Mangarataia, Mangarata',
 'Antiemetico (prevencao de nauseas e vomitos por cinetose), antidispeptico, carminativo. Estimulante digestivo, auxilia em colicas flatulentas.',
 'Contraindicado em calculos biliares, irritacao gastrica, hipertensao arterial. Nao recomendado para menores de 18 anos. Cautela com anticoagulantes e disturbios de coagulacao.',
 'Infusao: 0,5 a 1 g de rizoma fresco ralado em 150 mL de agua fervente. Po seco em capsulas.',
 'Rizoma seco em po: 1 a 2 g por dia. Infusao: 2 a 3 xicaras ao dia.',
 'Pode potencializar efeito de anticoagulantes. Disturbios gastrointestinais leves e cefaleia em doses elevadas.',
 'RENISUS. Farmacopeia Brasileira. Remedio homeopatico relacionado: Zingiber.'),

-- 8. Alho
('Alho',
 'Allium sativum L.',
 'Alho, Alho-branco, Alho-comum, Alho-manso',
 'Coadjuvante no tratamento de hiperlipidemia e hipertensao arterial leve. Antimicrobiano, antifungico, expectorante. Prevencao de aterosclerose.',
 'Contraindicado em hipersensibilidade. Cautela em gestantes, lactantes e pacientes em uso de anticoagulantes ou antiplaquetarios. Suspender 7 dias antes de cirurgias.',
 'Capsulas de oleo ou extrato seco padronizado em alicina. Uso culinario do bulbo fresco.',
 'Bulbo fresco: 1 a 4 g ao dia (1 a 4 dentes). Extrato seco: conforme padronizacao do fabricante.',
 'Potencializa efeito de anticoagulantes e antiplaquetarios. Pode reduzir eficacia de ciclosporina e inibidores de protease.',
 'RENISUS. Farmacopeia Brasileira. Remedio homeopatico relacionado: Allium sativum.'),

-- 9. Babosa
('Babosa',
 'Aloe vera (L.) Burm.f.',
 'Babosa, Aloe, Erva-babosa, Caraguata',
 'Uso externo: cicatrizante, anti-inflamatorio, hidratante em queimaduras e feridas. Uso interno (gel): laxativo, auxiliar na constipacao.',
 'Uso interno do latex contraindicado em gestantes (risco de aborto), lactantes, criancas, obstrucao intestinal, doencas inflamatorias intestinais e insuficiencia renal. Nao usar por periodos prolongados.',
 'Uso externo: gel fresco da folha aplicado diretamente sobre a pele. Uso interno: suco ou capsulas do gel purificado.',
 'Uso externo: aplicar o gel 2 a 3 vezes ao dia. Uso interno (laxativo): conforme orientacao medica.',
 'Uso interno pode causar desequilibrio eletrolitico (hipocalemia) e potencializar efeito de glicosideos cardiacos e diureticos.',
 'RENISUS. Farmacopeia Brasileira. Remedio homeopatico relacionado: Aloe socotrina.'),

-- 10. Boldo
('Boldo',
 'Peumus boldus Molina',
 'Boldo, Boldo-do-chile',
 'Colagogo, colerético. Auxilia na digestao, estimula a producao e excrecao de bile. Util em dispepsia, ma digestao e desconforto hepatico.',
 'Contraindicado em gestantes, lactantes, criancas, obstrucao das vias biliares, hepatopatias graves. Nao usar por periodos prolongados.',
 'Infusao: 1 a 2 g de folhas secas em 150 mL de agua fervente, abafar por 10 min.',
 'Cha: 1 xicara apos as refeicoes principais (2 a 3 vezes ao dia). Tintura: 20 a 40 gotas, 3 vezes ao dia.',
 'Potencializa efeito de anticoagulantes. Nao associar com bebidas alcoolicas.',
 'Farmacopeia Brasileira. Remedio homeopatico relacionado: Boldoa fragrans (Peumus boldus).'),

-- 11. Boldo-brasileiro
('Boldo-brasileiro',
 'Plectranthus barbatus Andrews',
 'Boldo-brasileiro, Boldo-nacional, Boldo-falso, Boldo-de-jardim, Falso-boldo',
 'Dispepsia, ma digestao, azia, flatulencia. Estimulante da digestao e colagogo.',
 'Contraindicado em gestantes e lactantes. Nao usar por periodos prolongados.',
 'Infusao: 2 a 3 folhas frescas em 150 mL de agua fervente, abafar por 10 min.',
 'Cha: 1 xicara antes ou apos as refeicoes, 2 a 3 vezes ao dia.',
 'Pode potencializar efeito de anti-hipertensivos.',
 'RENISUS. Remedio homeopatico relacionado: Coleus barbatus.'),

-- 12. Arnica (brasileira)
('Arnica brasileira',
 'Solidago microglossa DC.',
 'Arnica-brasileira, Arnica-silvestre, Erva-lanceta',
 'Anti-inflamatorio, analgesico, cicatrizante. Uso externo em contusoes, hematomas, edemas e dores musculares.',
 'Nao usar internamente. Contraindicado em gestantes e lactantes. Evitar em feridas abertas e pele lesionada.',
 'Uso externo: tintura ou infusao concentrada para compressas e cataplasmas.',
 'Tintura: aplicar sobre a regiao afetada 2 a 3 vezes ao dia. Compressas: embeber pano limpo na infusao e aplicar por 15-20 min.',
 'Uso interno pode causar irritacao gastrointestinal e nauseas.',
 'RENISUS. Remedio homeopatico relacionado: Arnica montana.'),

-- 13. Arnica montana
('Arnica montana',
 'Arnica montana L.',
 'Arnica, Arnica-verdadeira, Arnica-da-montanha',
 'Uso externo: contusoes, hematomas, edemas, dores musculares e articulares, traumas. Em homeopatia: traumatismos, pos-operatorio, fadiga muscular.',
 'Uso interno alopático contraindicado (toxica). Nao aplicar em feridas abertas. Contraindicada em hipersensibilidade a Asteraceae.',
 'Homeopatia: globulos ou gotas em diversas potencias (6CH, 12CH, 30CH). Uso externo: tintura diluida ou gel.',
 'Homeopatia: 5 globulos ou 3-5 gotas, 3 vezes ao dia na potencia indicada. Uso externo: aplicar gel ou tintura diluida 2 a 3 vezes ao dia.',
 'Em homeopatia, interacoes sao raras devido a alta diluicao. Uso externo fitoterápico: evitar em pele lesionada.',
 'Farmacopeia Homeopatica Brasileira. Um dos principais remedios homeopaticos. Relacionados: Arnica montana, Bellis perennis, Ruta graveolens.'),

-- 14. Calêndula
('Calendula',
 'Calendula officinalis L.',
 'Calendula, Mal-me-quer, Maravilha, Bem-me-quer',
 'Uso externo: anti-inflamatorio, cicatrizante, antisseptico. Util em feridas, queimaduras leves, dermatites, assaduras e ulceras de pele. Em homeopatia: cicatrizacao de feridas.',
 'Contraindicada em gestantes (uso interno). Hipersensibilidade a Asteraceae. Nao usar em feridas profundas ou infectadas sem orientacao medica.',
 'Infusao para uso externo: 1 a 2 g de flores secas em 150 mL de agua fervente. Tintura diluida para compressas. Homeopatia: tintura-mae ou dinamizacoes.',
 'Uso externo: lavar ou aplicar compressas 2 a 3 vezes ao dia. Homeopatia: Calendula officinalis TM ou 6CH, conforme indicacao.',
 'Pode potencializar efeito de sedativos e anti-hipertensivos quando em uso interno.',
 'RENISUS. Farmacopeia Homeopatica Brasileira. Remedios homeopaticos relacionados: Calendula officinalis.'),

-- 15. Quebra-pedra
('Quebra-pedra',
 'Phyllanthus niruri L.',
 'Quebra-pedra, Erva-pombinha, Fura-parede, Arrebenta-pedra',
 'Diuretico, litolitico (auxilia na eliminacao de calculos renais pequenos e acido urico). Acao antibacteriana, hipoglicemiante, antiespasmocida, hepatoprotetora.',
 'Contraindicada em gestantes, lactantes e criancas. Cautela em pacientes com hipotensao. Nao usar por periodos prolongados sem orientacao medica.',
 'Infusao: 3 g de partes aereas secas em 150 mL de agua fervente, abafar por 10 min. Decocao tambem pode ser utilizada.',
 'Cha: 1 xicara, 2 a 3 vezes ao dia, por periodo maximo de 3 semanas consecutivas.',
 'Pode potencializar efeito de anti-hipertensivos e hipoglicemiantes. Cautela com diureticos.',
 'RENISUS. Farmacopeia Brasileira. Remedio homeopatico relacionado: Phyllanthus niruri.'),

-- 16. Aroeira
('Aroeira',
 'Schinus terebinthifolius Raddi',
 'Aroeira, Aroeira-da-praia, Aroeira-vermelha, Aroeira-pimenteira, Pimenta-rosa',
 'Anti-inflamatorio e antisseptico vaginal. Util em cervicites, vaginites, afeccoes da pele e couro cabeludo causadas por fungos.',
 'Contraindicada em gestantes, lactantes, criancas menores de 2 anos, dependentes de alcool e diabeticos. Hipersensibilidade a Anacardiaceae.',
 'Uso externo: decocao da casca para banhos de assento. Gel vaginal padronizado. Tintura para uso topico.',
 'Gel vaginal: conforme orientacao medica. Banho de assento: decocao de 10 g de casca em 1 litro de agua, 1 a 2 vezes ao dia.',
 'Nao ha interacoes significativas descritas para uso externo.',
 'RENISUS/RENAME. Fitoterapico disponivel no SUS. Remedio homeopatico relacionado: Schinus terebinthifolius.'),

-- 17. Barbatimao
('Barbatimao',
 'Stryphnodendron adstringens (Mart.) Coville',
 'Barbatimao, Barba-de-timao, Casca-da-virgindade',
 'Uso externo: cicatrizante, adstringente, antisseptico. Util em feridas, ulceras cutaneas, leucorreia, hemorroidas.',
 'Nao usar quando existem drenos para retirada de fluidos corporais. Contraindicado em gestantes, lactantes e criancas. Semente e altamente toxica.',
 'Decocao da casca para lavagens e banhos de assento. Tintura para uso topico.',
 'Decocao: 3 g de cascas em 150 mL de agua, ferver por 10 min. Aplicar em compressas ou banhos de assento 2 a 3 vezes ao dia.',
 'Plantas ricas em taninos em doses excessivas podem causar irritacao da mucosa gastrica.',
 'RENISUS. Farmacopeia Brasileira. Remedio homeopatico relacionado: Stryphnodendron adstringens.'),

-- 18. Carqueja
('Carqueja',
 'Baccharis trimera (Less.) DC.',
 'Carqueja, Carqueja-amarga, Cacalia-amarga, Tiririca-de-babado',
 'Digestivo, hepatoprotetor, colagogo, anti-inflamatorio, hipoglicemiante. Auxilia em dispepsia, ma digestao e disturbios hepaticos.',
 'Contraindicada em gestantes (pode estimular contracoes uterinas), lactantes e hipotensas. Nao usar por periodos prolongados.',
 'Infusao: 2 a 3 g de partes aereas secas em 150 mL de agua fervente, abafar por 10 min.',
 'Cha: 1 xicara, 2 a 3 vezes ao dia, antes ou apos as refeicoes.',
 'Pode potencializar efeito de hipoglicemiantes e anti-hipertensivos.',
 'RENISUS. Remedio homeopatico relacionado: Baccharis trimera.'),

-- 19. Pata-de-vaca
('Pata-de-vaca',
 'Bauhinia forficata Link',
 'Pata-de-vaca, Unha-de-vaca, Unha-de-boi, Mororo',
 'Hipoglicemiante (auxiliar no controle da glicemia em diabetes tipo 2). Diuretico leve.',
 'Contraindicada em gestantes e lactantes. Cautela em pacientes que ja usam hipoglicemiantes orais ou insulina (risco de hipoglicemia).',
 'Infusao ou decocao: 1 a 2 folhas em 150 mL de agua. Capsulas de extrato seco.',
 'Cha: 1 xicara, 2 a 3 vezes ao dia. Decocao: ferver por 5 min e abafar.',
 'Pode potencializar efeito de hipoglicemiantes orais e insulina.',
 'RENISUS. Remedio homeopatico relacionado: Bauhinia forficata.'),

-- 20. Picao-preto
('Picao-preto',
 'Bidens pilosa L.',
 'Picao-preto, Picao, Carrapicho-de-agulha, Amor-seco',
 'Anti-inflamatorio, diuretico, antimicrobiano, hipoglicemiante. Auxilia em ictericia, hepatite e afeccoes das vias urinarias.',
 'Contraindicado em gestantes e lactantes. Cautela com hipoglicemiantes orais.',
 'Infusao: 2 a 3 g de partes aereas secas em 150 mL de agua fervente, abafar por 10 min.',
 'Cha: 1 xicara, 2 a 3 vezes ao dia.',
 'Pode potencializar efeito de hipoglicemiantes e anti-hipertensivos.',
 'RENISUS. Remedio homeopatico relacionado: Bidens pilosa.'),

-- 21. Andiroba
('Andiroba',
 'Carapa guianensis Aubl.',
 'Andiroba, Nandiroba, Andiroba-saruba',
 'Anti-inflamatorio, analgesico, repelente de insetos. Uso externo em contusoes, dores musculares, edemas e como cicatrizante.',
 'Evitar uso interno sem orientacao medica. Contraindicado em gestantes e lactantes.',
 'Oleo das sementes para massagens e uso topico. Velas e sabonetes medicamentosos.',
 'Uso externo: aplicar o oleo sobre a regiao afetada 2 a 3 vezes ao dia.',
 'Nao ha interacoes significativas descritas para uso externo.',
 'RENISUS. Planta da Amazonia brasileira.'),

-- 22. Guacatonga
('Guacatonga',
 'Casearia sylvestris Sw.',
 'Guacatonga, Guaçatonga, Erva-de-lagarto, Cha-de-bugre, Porangaba',
 'Anti-inflamatorio, antisseptico, cicatrizante, antiulceroso, depurativo. Util em afeccoes da pele e mucosas.',
 'Contraindicada em gestantes e lactantes. Doses elevadas podem causar sonolencia.',
 'Infusao: 1 a 2 g de folhas secas em 150 mL de agua fervente, abafar por 10 min. Tintura.',
 'Cha: 1 xicara, 2 a 3 vezes ao dia. Tintura: 20 a 40 gotas, 3 vezes ao dia.',
 'Pode potencializar efeito de anticoagulantes.',
 'RENISUS. Remedio homeopatico relacionado: Casearia sylvestris.'),

-- 23. Copaiba
('Copaiba',
 'Copaifera langsdorffii Desf.',
 'Copaiba, Oleo-de-copaiba, Pau-de-oleo, Balsamo-de-copaiba',
 'Anti-inflamatorio, cicatrizante, antisseptico, expectorante. Util em afeccoes respiratorias, feridas, ulceras e dores articulares.',
 'Contraindicada em gestantes e lactantes. Doses excessivas podem causar nauseas, vomitos e diarreia. Nao usar em criancas menores de 12 anos.',
 'Oleoresina para uso interno (gotas) ou externo (topico). Capsulas.',
 'Oleoresina: 3 a 5 gotas em agua ou mel, 2 a 3 vezes ao dia. Uso externo: aplicar diretamente sobre a regiao afetada.',
 'Pode potencializar efeito de anticoagulantes.',
 'RENISUS. Farmacopeia Brasileira. Planta da Amazonia brasileira.'),

-- 24. Erva-baleeira
('Erva-baleeira',
 'Cordia verbenacea DC.',
 'Erva-baleeira, Maria-milagrosa, Salicina, Catinga-de-barrao',
 'Anti-inflamatorio topico. Indicado para tendinites, dores musculares, contusoes e processos inflamatorios em geral.',
 'Contraindicada em gestantes, lactantes e criancas. Hipersensibilidade aos componentes.',
 'Creme ou pomada de uso topico padronizado em alfa-humuleno. Tintura para uso externo.',
 'Creme/pomada: aplicar sobre a regiao afetada 3 vezes ao dia, com leve massagem.',
 'Nao ha interacoes significativas descritas para uso externo.',
 'RENISUS/RENAME. Fitoterapico disponivel no SUS (Acheflan). Remedio homeopatico relacionado: Cordia verbenacea.'),

-- 25. Mulungu
('Mulungu',
 'Erythrina mulungu Mart. ex Benth.',
 'Mulungu, Murungu, Corticeira, Suina, Bico-de-papagaio',
 'Sedativo, ansiolitico, anticonvulsivante. Auxilia no tratamento de ansiedade, insonia e agitacao nervosa.',
 'Contraindicado em gestantes, lactantes e criancas. Pode causar sonolencia (evitar dirigir). Nao usar por periodos prolongados.',
 'Decocao: 4 a 6 g de cascas em 150 mL de agua, ferver por 10 min. Tintura.',
 'Cha: 1 xicara, 2 a 3 vezes ao dia, preferencialmente a noite. Tintura: 30 a 50 gotas, 2 a 3 vezes ao dia.',
 'Potencializa efeito de sedativos, ansioliticos e barbitúricos.',
 'RENISUS. Planta nativa do Brasil.'),

-- 26. Unha-de-gato
('Unha-de-gato',
 'Uncaria tomentosa (Willd. ex Schult.) DC.',
 'Unha-de-gato, Espera-ai, Jupinda',
 'Anti-inflamatorio, imunomodulador, antioxidante. Auxilia no tratamento de artrite, processos inflamatorios cronicos e como adjuvante em terapias oncologicas.',
 'Contraindicada em gestantes, lactantes, criancas menores de 12 anos e pacientes imunossuprimidos. Nao usar antes de cirurgias (efeito anticoagulante).',
 'Decocao: 10 g de casca em 500 mL de agua, ferver por 15 min. Capsulas de extrato seco.',
 'Cha: 1 xicara, 2 a 3 vezes ao dia. Capsulas: conforme orientacao medica e padronizacao do fabricante.',
 'Pode interagir com anticoagulantes, anti-hipertensivos e imunossupressores.',
 'RENISUS. Remedio homeopatico relacionado: Uncaria tomentosa.'),

-- 27. Ipê-roxo
('Ipe-roxo',
 'Handroanthus impetiginosus (Mart. ex DC.) Mattos',
 'Ipe-roxo, Pau-d''arco, Lapacho, Piuva',
 'Anti-inflamatorio, antimicrobiano, antifungico, antitumoral (adjuvante). Util em infeccoes, candidíase e como imunoestimulante.',
 'Contraindicado em gestantes, lactantes e criancas. Doses elevadas podem causar nauseas, vomitos e aumento do tempo de coagulacao. Nao usar com anticoagulantes.',
 'Decocao: 10 a 15 g de casca interna seca em 500 mL de agua, ferver por 15 min. Capsulas de extrato seco.',
 'Cha: 1 xicara, 2 a 3 vezes ao dia. Capsulas: conforme orientacao medica.',
 'Pode potencializar efeito de anticoagulantes e antiplaquetarios.',
 'RENISUS. Farmacopeia Brasileira. Remedio homeopatico relacionado: Tabebuia avellanedae.'),

-- 28. Mil-folhas
('Mil-folhas',
 'Achillea millefolium L.',
 'Mil-folhas, Dipirona, Mil-em-rama, Erva-de-cortaduras, Aquileia',
 'Anti-inflamatorio, antiespasmocido, digestivo, cicatrizante, emenagogo. Auxilia em dispepsia, colicas e como anti-hemorragico.',
 'Contraindicada em gestantes (efeito emenagogo), lactantes e hipersensibilidade a Asteraceae. Pode causar dermatite de contato.',
 'Infusao: 1 a 2 g de partes aereas floridas em 150 mL de agua fervente, abafar por 10 min.',
 'Cha: 1 xicara, 3 vezes ao dia. Tintura: 20 a 40 gotas, 3 vezes ao dia.',
 'Pode potencializar efeito de anticoagulantes e sedativos.',
 'RENISUS. Farmacopeia Brasileira. Remedio homeopatico relacionado: Millefolium.'),

-- 29. Caju
('Caju',
 'Anacardium occidentale L.',
 'Caju, Cajueiro, Acaju',
 'Anti-inflamatorio, adstringente, hipoglicemiante. A casca é usada em afeccoes da garganta, diarreias e como antissepitico.',
 'Contraindicado em pessoas alergicas a Anacardiaceae. A casca da castanha e caustica e nao deve ser aplicada diretamente na pele.',
 'Decocao: 10 g de cascas do tronco em 500 mL de agua, ferver por 10 min. Gargarejo com a decocao.',
 'Gargarejo ou bochecho: 2 a 3 vezes ao dia. Cha: 1 xicara, 2 a 3 vezes ao dia.',
 'Pode potencializar efeito de hipoglicemiantes.',
 'RENISUS. Remedio homeopatico relacionado: Anacardium occidentale.'),

-- 30. Hortelã
('Hortela',
 'Mentha x piperita L.',
 'Hortela, Hortela-pimenta, Menta, Hortela-apimentada',
 'Antiespasmocido, carminativo, analgesico, descongestionante nasal. Auxilia em dispepsia, flatulencia, nauseas e cefaleia.',
 'Contraindicada em obstrucao de vias biliares, inflamacao da vesicula biliar, dano hepatico grave. Cautela em gestantes e lactantes. Oleo essencial nao deve ser usado em criancas menores de 2 anos.',
 'Infusao: 1 a 2 g de folhas secas em 150 mL de agua fervente, abafar por 10 min. Oleo essencial para inalacao.',
 'Cha: 1 xicara, 3 a 4 vezes ao dia. Oleo essencial: 1 a 2 gotas em inalacao.',
 'Pode reduzir absorcao de ferro. Oleo essencial pode interagir com ciclosporina.',
 'RENISUS. Farmacopeia Brasileira. Remedio homeopatico relacionado: Mentha piperita.'),

-- 31. Tanchagem
('Tanchagem',
 'Plantago major L.',
 'Tanchagem, Transagem, Trancagem, Lingua-de-vaca, Sete-nervos',
 'Anti-inflamatorio, cicatrizante, adstringente, expectorante. Util em afeccoes da garganta, boca e trato respiratorio.',
 'Contraindicada em gestantes e lactantes. Hipersensibilidade aos componentes. Pode causar obstrucao intestinal em doses elevadas das sementes.',
 'Infusao: 3 a 6 g de folhas secas em 150 mL de agua fervente, abafar por 10 min. Gargarejo com infusao.',
 'Cha ou gargarejo: 2 a 3 vezes ao dia.',
 'Pode reduzir absorcao de medicamentos administrados concomitantemente (fibras mucilaginosas).',
 'RENISUS. Farmacopeia Brasileira. Remedio homeopatico relacionado: Plantago major.'),

-- 32. Roma
('Roma',
 'Punica granatum L.',
 'Roma, Romanzeira, Romeira',
 'Adstringente, anti-inflamatorio, antimicrobiano. Util em infeccoes da garganta, gengivite, estomatite e faringite.',
 'Contraindicada em gestantes e lactantes. Doses elevadas da casca do fruto podem causar toxicidade. Nao usar por periodos prolongados.',
 'Decocao da casca do fruto: 6 g em 150 mL de agua, ferver por 10 min. Gargarejo ou bochecho com a decocao.',
 'Gargarejo: 3 a 4 vezes ao dia. Nao ingerir a decocao da casca em grandes quantidades.',
 'Pode potencializar efeito de anti-hipertensivos e anticoagulantes.',
 'RENISUS. Farmacopeia Brasileira. Remedio homeopatico relacionado: Punica granatum.'),

-- 33. Cascara-sagrada
('Cascara-sagrada',
 'Rhamnus purshiana DC.',
 'Cascara-sagrada, Cascara, Sagrada',
 'Laxativo estimulante. Indicada na constipacao intestinal ocasional.',
 'Contraindicada em gestantes, lactantes, criancas menores de 12 anos, obstrucao intestinal, doencas inflamatorias intestinais, apendicite, dor abdominal de origem desconhecida. Nao usar por mais de 1 a 2 semanas.',
 'Capsulas ou comprimidos de extrato seco padronizado em cascarosideos.',
 'Capsulas: conforme orientacao medica, geralmente 20 a 30 mg de derivados hidroxiantraceicos ao dia, preferencialmente a noite.',
 'Pode reduzir absorcao de medicamentos orais. Uso prolongado pode causar dependencia e disturbios eletroliticos (hipocalemia).',
 'RENISUS. Farmacopeia Brasileira. Remedio homeopatico relacionado: Rhamnus purshiana.'),

-- 34. Arruda
('Arruda',
 'Ruta graveolens L.',
 'Arruda, Arruda-fetida, Arruda-domestica, Ruta',
 'Emenagoga, antiespasmocida, vermifuga. Uso externo como repelente de insetos. Em homeopatia: traumatismos tendinosos, dores oculares.',
 'ALTAMENTE contraindicada em gestantes (abortiva). Contraindicada em lactantes e criancas. O contato com a pele sob exposicao solar causa fitofotodermatite grave.',
 'Uso externo apenas. Homeopatia: globulos ou gotas em potencias dinamizadas.',
 'Homeopatia: Ruta graveolens 6CH a 30CH, 5 globulos 3 vezes ao dia. Uso topico: evitar exposicao solar.',
 'Em homeopatia, interacoes sao raras. Uso fitoterápico: risco de fitofotodermatite.',
 'RENISUS. Farmacopeia Homeopatica Brasileira. Remedios homeopaticos relacionados: Ruta graveolens.'),

-- 35. Salgueiro
('Salgueiro',
 'Salix alba L.',
 'Salgueiro, Salgueiro-branco, Chorão, Vime',
 'Anti-inflamatorio, analgesico, antipiretico (similar a aspirina). Auxilia em dores leves a moderadas, febre e dores articulares.',
 'Contraindicado em hipersensibilidade a salicilatos (aspirina), gestantes, lactantes, criancas e adolescentes (risco de sindrome de Reye). Ulcera gastrica ativa.',
 'Decocao: 2 a 3 g de cascas em 150 mL de agua, ferver por 10 min. Extrato seco padronizado em salicina.',
 'Cha: 1 xicara, 2 a 3 vezes ao dia. Extrato seco: 60 a 120 mg de salicina ao dia.',
 'Potencializa efeito de anticoagulantes, anti-inflamatorios e antiplaquetarios. Nao associar com aspirina.',
 'RENISUS. Farmacopeia Brasileira. Remedio homeopatico relacionado: Salix alba.'),

-- 36. Goiabeira
('Goiabeira',
 'Psidium guajava L.',
 'Goiabeira, Goiaba, Araça-guacu',
 'Antidiarreico, adstringente, antimicrobiano. Util no tratamento de diarreias, disenterias e como antissepitico bucal.',
 'Contraindicada em casos de constipacao intestinal cronica. Cautela em gestantes e lactantes.',
 'Decocao das folhas: 10 g em 500 mL de agua, ferver por 10 min. Uso como cha ou gargarejo.',
 'Cha: 1 xicara, 3 a 4 vezes ao dia. Gargarejo: 3 vezes ao dia.',
 'Pode potencializar efeito de antidiarreicos.',
 'RENISUS. Farmacopeia Brasileira. Remedio homeopatico relacionado: Psidium guajava.'),

-- 37. Jurubeba
('Jurubeba',
 'Solanum paniculatum L.',
 'Jurubeba, Jubeba, Juripeba, Jurupeba',
 'Digestivo, hepatoprotetor, colagogo, coleretico. Auxilia em disturbios gastricos e hepaticos, anemia e como tonico.',
 'Contraindicada em gestantes, lactantes e criancas. Doses elevadas podem causar irritacao gastrica.',
 'Infusao: 2 a 3 g de folhas ou frutos secos em 150 mL de agua fervente, abafar por 10 min. Tintura.',
 'Cha: 1 xicara antes das refeicoes, 2 a 3 vezes ao dia. Tintura: 20 a 30 gotas, 3 vezes ao dia.',
 'Pode potencializar efeito de hepatoprotetores.',
 'RENISUS. Planta nativa do Brasil. Remedio homeopatico relacionado: Solanum paniculatum.'),

-- 38. Jambolao
('Jambolao',
 'Syzygium cumini (L.) Skeels',
 'Jambolao, Jamelao, Jambeiro, Jambo',
 'Hipoglicemiante, adstringente, anti-inflamatorio. Auxilia no controle da glicemia em diabetes tipo 2.',
 'Contraindicado em gestantes, lactantes e criancas. Cautela com hipoglicemiantes orais e insulina.',
 'Decocao: 10 g de cascas ou sementes em 500 mL de agua, ferver por 10 min. Po das sementes em capsulas.',
 'Cha: 1 xicara, 2 a 3 vezes ao dia. Po das sementes: 1 a 3 g ao dia.',
 'Pode potencializar efeito de hipoglicemiantes orais e insulina.',
 'RENISUS. Remedio homeopatico relacionado: Syzygium jambolanum.'),

-- 39. Cavalinha
('Cavalinha',
 'Equisetum arvense L.',
 'Cavalinha, Rabo-de-cavalo, Milho-de-cobra, Cauda-de-cavalo',
 'Diuretico, remineralizante (rico em silicio), anti-inflamatorio. Auxilia em edemas, infeccoes urinarias leves e como fortalecedor de cabelos e unhas.',
 'Contraindicada em gestantes, lactantes, criancas, insuficiencia renal e cardiaca. Nao usar por periodos prolongados (risco de deficiencia de tiamina).',
 'Decocao: 2 a 3 g de partes aereas secas em 150 mL de agua, ferver por 5 min e abafar por 10 min.',
 'Cha: 1 xicara, 2 a 3 vezes ao dia, por periodo maximo de 4 semanas.',
 'Pode potencializar efeito de diureticos e anti-hipertensivos. Pode reduzir niveis de tiamina com uso prolongado.',
 'Farmacopeia Brasileira. Remedio homeopatico relacionado: Equisetum hyemale.'),

-- 40. Erva-de-Sao-Joao
('Erva-de-Sao-Joao',
 'Hypericum perforatum L.',
 'Erva-de-Sao-Joao, Hiperico, Erva-de-Sao-Joao-verdadeiro',
 'Antidepressivo em depressao leve a moderada. Ansiedade, disturbios do sono.',
 'Contraindicada em criancas, gestantes, lactantes, depressao grave. Fotossensibilidade (evitar exposicao solar prolongada).',
 'Capsulas de extrato seco padronizado em hipericina. Tintura.',
 'Extrato seco: 300 mg (padronizado em 0,3% hipericina), 3 vezes ao dia. Efeito terapêutico inicia apos 2 a 4 semanas.',
 'MULTIPLAS INTERACOES: reduz eficacia de anticoncepcionais, anticoagulantes (varfarina), ciclosporina, antirretrovirais, digoxina e antidepressivos (sindrome serotoninergica).',
 'Farmacopeia Brasileira. Fitoterapico com tarja vermelha (exige prescricao). Remedio homeopatico relacionado: Hypericum perforatum.'),

-- 41. Cimicifuga
('Cimicifuga',
 'Actaea racemosa L.',
 'Cimicifuga, Black cohosh, Erva-de-Sao-Cristovao',
 'Alivio dos sintomas da menopausa (fogachos, sudorese, alteracoes de humor, ansiedade). Dismenorreia.',
 'Contraindicada em gestantes, lactantes, hipersensibilidade. Contraindicada em portadores de insuficiencia hepatica. Exige prescricao medica.',
 'Capsulas de extrato seco padronizado. Comprimidos.',
 'Extrato seco: conforme padronizacao do fabricante e orientacao medica.',
 'Pode interagir com terapia hormonal e hepatotoxicos.',
 'Farmacopeia Brasileira. Fitoterapico com tarja vermelha. Remedio homeopatico relacionado: Cimicifuga racemosa.'),

-- 42. Guarana
('Guarana',
 'Paullinia cupana Kunth',
 'Guarana, Guaranazeiro, Uarana',
 'Estimulante do sistema nervoso central, combate fadiga e cansaco cronico. Estimulante cognitivo.',
 'Contraindicado em criancas, hipertensos, portadores de arritmia cardiaca, gastrite, ulcera, colon irritavel, hipertireoidismo, cirrose, insuficiencia renal e predisposicao a espasmos musculares.',
 'Po das sementes torradas em capsulas ou dissolvido em agua.',
 'Po: 0,5 a 2 g ao dia, divididos em 2 a 3 tomadas. Nao usar apos as 16h.',
 'Potencializa efeito de estimulantes e cafeina. Pode reduzir efeito de sedativos. Pode potencializar efeito de anticoagulantes.',
 'Farmacopeia Brasileira. Planta nativa da Amazonia.'),

-- 43. Alfavacao
('Alfavacao',
 'Ocimum gratissimum L.',
 'Alfavacao, Alfavaca-cravo, Alfavaca-do-mato, Manjericao-cheiroso',
 'Calmante, antiespasmocido, expectorante. Auxilia em sintomas respiratorios, dores, inflamacoes e como digestivo.',
 'Contraindicada em gestantes e lactantes. O oleo essencial pode ser irritante em concentracoes elevadas.',
 'Infusao: 2 a 3 g de folhas secas em 150 mL de agua fervente, abafar por 10 min.',
 'Cha: 1 xicara, 2 a 3 vezes ao dia.',
 'Pode potencializar efeito de sedativos.',
 'RENISUS. Remedio homeopatico relacionado: Ocimum.'),

-- 44. Alecrim-pimenta
('Alecrim-pimenta',
 'Lippia sidoides Cham.',
 'Alecrim-pimenta, Alecrim-do-nordeste, Estrepa-cavalo',
 'Antisseptico, antimicrobiano, anti-inflamatorio. Util em afeccoes bucais (gengivite, estomatite) e infeccoes de pele.',
 'Contraindicado em gestantes, lactantes e criancas menores de 2 anos. O oleo essencial puro nao deve ser aplicado diretamente na pele.',
 'Infusao para gargarejo ou bochecho: 2 a 3 g de folhas em 150 mL de agua fervente. Tintura diluida.',
 'Gargarejo ou bochecho: 3 a 4 vezes ao dia apos higiene bucal.',
 'Nao ha interacoes significativas descritas para uso topico.',
 'RENISUS. Planta nativa do nordeste brasileiro.'),

-- 45. Alecrim
('Alecrim',
 'Rosmarinus officinalis L.',
 'Alecrim, Alecrim-de-jardim, Alecrim-comum, Rosmaninho',
 'Estimulante circulatorio, digestivo, antiespasmocido, anti-inflamatorio. Auxilia em cefaleias, fadiga mental e dores reumaticas.',
 'Contraindicado em gestantes (emenagogo), lactantes. Doses elevadas podem causar convulsoes. Evitar em epilepticos.',
 'Infusao: 2 a 4 g de folhas secas em 150 mL de agua fervente, abafar por 10 min. Oleo essencial para uso externo.',
 'Cha: 1 xicara, 2 a 3 vezes ao dia. Uso externo: oleo diluido para massagem.',
 'Pode potencializar efeito de anticoagulantes e anti-hipertensivos.',
 'Farmacopeia Brasileira. Remedio homeopatico relacionado: Rosmarinus officinalis.'),

-- 46. Nux vomica
('Nux vomica',
 'Strychnos nux-vomica L.',
 'Noz-vomica, Nux vomica',
 'Em homeopatia: disturbios digestivos (indigestao, azia, nauseas), irritabilidade, estresse, ressaca, insonia por excesso de atividade mental, constipacao.',
 'USO EXCLUSIVAMENTE HOMEOPATICO (planta altamente toxica - contem estricnina). Contraindicado uso fitoterapico.',
 'Homeopatia: globulos, gotas ou comprimidos em potencias dinamizadas (6CH, 12CH, 30CH e superiores).',
 'Homeopatia: 5 globulos ou 3 a 5 gotas, 2 a 3 vezes ao dia na potencia indicada pelo homeopata.',
 'Em homeopatia, interacoes sao raras devido a ultra-diluicao.',
 'Farmacopeia Homeopatica Brasileira. Um dos policrestos mais importantes da materia medica homeopatica.'),

-- 47. Belladonna
('Belladonna',
 'Atropa belladonna L.',
 'Beladona, Belladonna, Erva-moura-mortal',
 'Em homeopatia: febres altas de inicio subito, dores de garganta, otite, cefaleia pulsante, insolacao, convulsoes febris, inflamacoes agudas com vermelhidao e calor.',
 'USO EXCLUSIVAMENTE HOMEOPATICO (planta altamente toxica). Contraindicado uso fitoterapico sem orientacao especializada.',
 'Homeopatia: globulos, gotas ou comprimidos em potencias dinamizadas (6CH, 12CH, 30CH e superiores).',
 'Homeopatia: 5 globulos ou 3 a 5 gotas, a cada 1 a 2 horas em quadros agudos, espacando conforme melhora.',
 'Em homeopatia, interacoes sao raras devido a ultra-diluicao.',
 'Farmacopeia Homeopatica Brasileira. Farmacopeia Brasileira. Policresto homeopatico fundamental.'),

-- 48. Bryonia
('Bryonia',
 'Bryonia alba L.',
 'Brionia, Nabo-do-diabo',
 'Em homeopatia: dores que pioram com movimento e melhoram com repouso, tosse seca dolorosa, cefaleia, artrite, constipacao, gripes com secura de mucosas.',
 'USO EXCLUSIVAMENTE HOMEOPATICO (planta toxica). Contraindicado uso fitoterapico.',
 'Homeopatia: globulos, gotas ou comprimidos em potencias dinamizadas (6CH, 12CH, 30CH e superiores).',
 'Homeopatia: 5 globulos ou 3 a 5 gotas, 3 vezes ao dia na potencia indicada pelo homeopata.',
 'Em homeopatia, interacoes sao raras devido a ultra-diluicao.',
 'Farmacopeia Homeopatica Brasileira. Policresto homeopatico.'),

-- 49. Pulsatilla
('Pulsatilla',
 'Pulsatilla nigricans Stork.',
 'Pulsatila, Anêmona-dos-prados, Flor-do-vento',
 'Em homeopatia: congestao nasal com secrecao espessa amarelada, otite media, disturbios menstruais, varicosidades, choro facil, sintomas que mudam de lugar.',
 'USO EXCLUSIVAMENTE HOMEOPATICO. Contraindicado uso fitoterapico.',
 'Homeopatia: globulos, gotas ou comprimidos em potencias dinamizadas (6CH, 12CH, 30CH e superiores).',
 'Homeopatia: 5 globulos ou 3 a 5 gotas, 3 vezes ao dia na potencia indicada pelo homeopata.',
 'Em homeopatia, interacoes sao raras devido a ultra-diluicao.',
 'Farmacopeia Homeopatica Brasileira. Policresto homeopatico. Afinidade com constituicao feminina.'),

-- 50. Hortelã-da-folha-grossa
('Hortela-da-folha-grossa',
 'Plectranthus amboinicus (Lour.) Spreng.',
 'Hortela-da-folha-grossa, Hortela-graca, Malvarisco, Malva-de-cheiro',
 'Broncodilatador, expectorante, antitussigeno. Auxilia no alivio da tosse, rouquidao e afeccoes respiratorias.',
 'Contraindicada em gestantes, lactantes e criancas menores de 2 anos.',
 'Infusao: 3 a 4 folhas frescas em 150 mL de agua fervente, abafar por 10 min.',
 'Cha: 1 xicara, 3 a 4 vezes ao dia.',
 'Pode potencializar efeito de outros expectorantes e mucoliticos.',
 'RENISUS. Planta amplamente cultivada no Brasil.'),

-- 51. Cana-do-brejo
('Cana-do-brejo',
 'Costus spicatus (Jacq.) Sw.',
 'Cana-do-brejo, Cana-de-macaco, Canafistula, Pobre-velho',
 'Diuretico, anti-inflamatorio urinario, litolitico. Auxilia em infeccoes urinarias, calculos renais e como depurativo.',
 'Contraindicada em gestantes, lactantes e portadores de insuficiencia renal grave.',
 'Decocao: 10 g de hastes frescas em 500 mL de agua, ferver por 5 min. Infusao das folhas.',
 'Cha: 1 xicara, 3 vezes ao dia.',
 'Pode potencializar efeito de diureticos e anti-hipertensivos.',
 'RENISUS. Planta nativa do Brasil.'),

-- 52. Erva-cidreira
('Erva-cidreira',
 'Lippia alba (Mill.) N.E.Br. ex Britton & P.Wilson',
 'Erva-cidreira, Erva-cidreira-brasileira, Cidreira, Falsa-melissa',
 'Calmante, sedativo leve, antiespasmocido, carminativo, analgesico. Auxilia em ansiedade, insonia, colicas e disturbios digestivos.',
 'Contraindicada em gestantes, lactantes. Pode causar sonolencia (evitar dirigir).',
 'Infusao: 1 a 3 g de folhas secas em 150 mL de agua fervente, abafar por 10 min.',
 'Cha: 1 xicara, 2 a 3 vezes ao dia, preferencialmente a noite.',
 'Potencializa efeito de sedativos e ansioliticos.',
 'RENISUS. Planta amplamente cultivada no Brasil. Remedio homeopatico relacionado: Lippia alba.'),

-- 53. Melissa
('Melissa',
 'Melissa officinalis L.',
 'Melissa, Erva-cidreira-verdadeira, Cidreira, Cha-de-franca',
 'Sedativo leve, ansiolitico, antiespasmocido, antiviral (herpes labial). Auxilia em ansiedade, insonia e disturbios digestivos nervosos.',
 'Contraindicada em hipotireoidismo (pode suprimir funcao tireoidiana). Cautela em gestantes e lactantes.',
 'Infusao: 2 a 4 g de folhas secas em 150 mL de agua fervente, abafar por 10 min.',
 'Cha: 1 xicara, 2 a 3 vezes ao dia. Uso topico (herpes): creme a 1% de extrato liofilizado.',
 'Pode potencializar efeito de sedativos, barbitúricos e medicamentos tireoidianos.',
 'Farmacopeia Brasileira. Remedio homeopatico relacionado: Melissa officinalis.'),

-- 54. Valeriana
('Valeriana',
 'Valeriana officinalis L.',
 'Valeriana, Erva-de-sao-jorge, Erva-de-gato',
 'Sedativo, ansiolitico, indutor do sono. Auxilia no tratamento de insonia, ansiedade e agitacao nervosa.',
 'Contraindicada em criancas menores de 12 anos, gestantes e lactantes. Pode causar sonolencia (evitar dirigir e operar maquinas). Nao associar com alcool.',
 'Capsulas de extrato seco padronizado em acido valerenico. Infusao da raiz.',
 'Extrato seco: 45 a 125 mg de acido valerenico, 1 a 3 vezes ao dia. Infusao da raiz: 1 a 3 g em 150 mL, 30 min antes de dormir.',
 'Potencializa efeito de sedativos, barbitúricos e benzodiazepinicos. Pode potencializar efeito do alcool.',
 'Farmacopeia Brasileira. Remedio homeopatico relacionado: Valeriana officinalis.'),

-- 55. Hamamelis
('Hamamelis',
 'Hamamelis virginiana L.',
 'Hamamelis, Hamamelis-da-virginia, Aveleira-de-bruxa',
 'Adstringente, anti-inflamatorio, vasoconstritor venoso. Util em hemorroidas, varizes, pernas cansadas, dermatite e como hemostático.',
 'Contraindicada em hipersensibilidade. Uso interno deve ser evitado em gestantes, lactantes e criancas. Uso prolongado pode causar constipacao.',
 'Uso externo: agua de hamamelis ou decocao para compressas. Capsulas de extrato seco para uso interno.',
 'Uso externo: aplicar compressas 2 a 3 vezes ao dia. Capsulas: conforme orientacao medica.',
 'Pode reduzir absorcao de medicamentos orais (taninos). Pode potencializar efeito de anticoagulantes.',
 'Farmacopeia Brasileira. Remedio homeopatico relacionado: Hamamelis virginiana.');

-- Verificar contagem
-- SELECT COUNT(*) FROM "PhytotherapyPlant";
