#!/usr/bin/env python3
"""Fix all missing accents in the guide generator script."""
import re

path = r'C:\Users\Carlos Honorato\OneDrive\Área de trabalho\SIHOREMAX7\HomeoClinicPro-Projeto\docs\generate_guia.py'
with open(path, 'r', encoding='utf-8') as f:
    content = f.read()

# Simple word-level replacements (only within string content)
fixes = {
    'Sumario': 'Sumário',
    'Clinica': 'Clínica',
    'clinica': 'clínica',
    'Homeopatica': 'Homeopática',
    'homeopatica': 'homeopática',
    'Transcricao': 'Transcrição',
    'transcricao': 'transcrição',
    'Prontuario': 'Prontuário',
    'prontuario': 'prontuário',
    'Repertorio': 'Repertório',
    'repertorio': 'repertório',
    'Repertorizacao': 'Repertorização',
    'repertorizacao': 'repertorização',
    'Configuracoes': 'Configurações',
    'configuracoes': 'configurações',
    'Dicionario': 'Dicionário',
    'dicionario': 'dicionário',
    'Analitico': 'Analítico',
    'obrigatorio': 'obrigatório',
    'Endereco': 'Endereço',
    'endereco': 'endereço',
    'Clinicos': 'Clínicos',
    'clinicos': 'clínicos',
    'Profissao': 'Profissão',
    'profissao': 'profissão',
    'Convenio': 'Convênio',
    'convenio': 'convênio',
    'Observacoes': 'Observações',
    'observacoes': 'observações',
    'nao sera possivel': 'não será possível',
    'exclusao': 'exclusão',
    'exigencia': 'exigência',
    'Classica': 'Clássica',
    'Pediatrica': 'Pediátrica',
    'Obstetricia': 'Obstetrícia',
    'secao': 'seção',
    'secoes': 'seções',
    'memoria': 'memória',
    'Aversoes': 'Aversões',
    'Transpiracao': 'Transpiração',
    'transpiracao': 'transpiração',
    'localizacao': 'localização',
    'Termorregulacao': 'Termorregulação',
    'Preferencia termica': 'Preferência térmica',
    'tolerancia': 'tolerância',
    'Ginecologico': 'Ginecológico',
    'titulo': 'título',
    'sugestao': 'sugestão',
    'audio': 'áudio',
    'sera inserido': 'será inserido',
    'Prescricao': 'Prescrição',
    'prescricao': 'prescrição',
    'Evolucao': 'Evolução',
    'evolucao': 'evolução',
    'historico': 'histórico',
    'capitulos': 'capítulos',
    'paginacao': 'paginação',
    'graduacao': 'graduação',
    'importancia': 'importância',
    'portugues': 'português',
    'ingles': 'inglês',
    'selecao': 'seleção',
    'Materia': 'Matéria',
    'materia': 'matéria',
    'remedio': 'remédio',
    'conteudo': 'conteúdo',
    'metodo': 'método',
    'Algoritmico': 'Algorítmico',
    'Potencia': 'Potência',
    'potencia': 'potência',
    'Frequencia': 'Frequência',
    'frequencia': 'frequência',
    'Raciocinio Clinico': 'Raciocínio Clínico',
    'decisao': 'decisão',
    'saude': 'saúde',
    'Proximo': 'Próximo',
    'proximo': 'próximo',
    'Diaria': 'Diária',
    'horarios': 'horários',
    'Horario': 'Horário',
    'horario': 'horário',
    'Duracao': 'Duração',
    'duracao': 'duração',
    'proximas': 'próximas',
    'Titulo': 'Título',
    'anonimos': 'anônimos',
    'Receituario': 'Receituário',
    'Relatorio': 'Relatório',
    'relatorio': 'relatório',
    'periodo': 'período',
    'impressao': 'impressão',
    'Descricao': 'Descrição',
    'acoes': 'ações',
    'acao': 'ação',
    'usuario': 'usuário',
    'Gestao': 'Gestão',
    'Medico': 'Médico',
    'medico': 'médico',
    'Comunicacoes': 'Comunicações',
    'Exportacao': 'Exportação',
    'Anonimizacao': 'Anonimização',
    'codigos': 'códigos',
    'estatistica': 'estatística',
    'Faca': 'Faça',
    'Pagina': 'Página',
    'minusculas': 'minúsculas',
    'minuscula': 'minúscula',
    'maiuscula': 'maiúscula',
    'numero': 'número',
    'Voce sera': 'Você será',
    'Cabeca': 'Cabeça',
    'pes': 'pés',
    'Mes': 'Mês',
    'dialogo': 'diálogo',
    'Atestado Medico': 'Atestado Médico',
    'informacoes': 'informações',
    'Guia de Uso': 'Guia de Uso',
    'Pediatria Homeopatica': 'Pediatria Homeopática',
}

count = 0
for old, new in fixes.items():
    if old in content:
        content = content.replace(old, new)
        count += 1

with open(path, 'w', encoding='utf-8') as f:
    f.write(content)

print(f"Applied {count} accent fixes")
